"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_spatial_pose(object):

    __slots__ = ["utime", "position", "orientation"]

    __typenames__ = ["int64_t", "double", "double"]

    __dimensions__ = [None, [3], [4]]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.position = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.orientation = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: double[4] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_spatial_pose._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>3d', *self.position[:3]))
        buf.write(struct.pack('>4d', *self.orientation[:4]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_spatial_pose._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_spatial_pose._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_spatial_pose()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.position = struct.unpack('>3d', buf.read(24))
        self.orientation = struct.unpack('>4d', buf.read(32))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_spatial_pose in parents: return 0
        tmphash = (0xa4a05c696026db9c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_spatial_pose._packed_fingerprint is None:
            lcmt_spatial_pose._packed_fingerprint = struct.pack(">Q", lcmt_spatial_pose._get_hash_recursive([]))
        return lcmt_spatial_pose._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_spatial_pose._get_packed_fingerprint())[0]

