"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_round_belt_state(object):

    __slots__ = ["utime", "frame_name", "num_control_points", "control_point_positions", "num_points", "point_positions"]

    __typenames__ = ["int64_t", "string", "int32_t", "float", "int32_t", "float"]

    __dimensions__ = [None, None, None, ["num_control_points", 3], None, ["num_points", 3]]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.frame_name = ""
        """
        Name of the coordinate frame this data is expressed in
        LCM Type: string
        """

        self.num_control_points = 0
        """ LCM Type: int32_t """
        self.control_point_positions = []
        """
        control points of the spline
        LCM Type: float[num_control_points][3]
        """

        self.num_points = 0
        """ LCM Type: int32_t """
        self.point_positions = []
        """
        xyz positions of points
        LCM Type: float[num_points][3]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_round_belt_state._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __frame_name_encoded = self.frame_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__frame_name_encoded)+1))
        buf.write(__frame_name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.num_control_points))
        for i0 in range(self.num_control_points):
            buf.write(struct.pack('>3f', *self.control_point_positions[i0][:3]))
        buf.write(struct.pack(">i", self.num_points))
        for i0 in range(self.num_points):
            buf.write(struct.pack('>3f', *self.point_positions[i0][:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_round_belt_state._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_round_belt_state._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_round_belt_state()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __frame_name_len = struct.unpack('>I', buf.read(4))[0]
        self.frame_name = buf.read(__frame_name_len)[:-1].decode('utf-8', 'replace')
        self.num_control_points = struct.unpack(">i", buf.read(4))[0]
        self.control_point_positions = []
        for i0 in range(self.num_control_points):
            self.control_point_positions.append(struct.unpack('>3f', buf.read(12)))
        self.num_points = struct.unpack(">i", buf.read(4))[0]
        self.point_positions = []
        for i0 in range(self.num_points):
            self.point_positions.append(struct.unpack('>3f', buf.read(12)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_round_belt_state in parents: return 0
        tmphash = (0xd0f0bfb7c724d3af) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_round_belt_state._packed_fingerprint is None:
            lcmt_round_belt_state._packed_fingerprint = struct.pack(">Q", lcmt_round_belt_state._get_hash_recursive([]))
        return lcmt_round_belt_state._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_round_belt_state._get_packed_fingerprint())[0]

