"""Newton port of the Drake round-belt scene, split by concern.

    constants.py    typed view over the scene directives YAML (where every number lives)
    directives.py   the round-belt extension directives (EXTENSION_DIRECTIVES)
    scene.py        load_directives on that YAML, mapped onto SceneInfo
    joint_state.py  seeding the finalized Model with the Drake default joint state
    simulation.py   RoundBeltTaskSimulation: solver, stepping, CUDA graph, diagnostics

``round_belt_task_simulation.py`` at the repo root is the entry point.  The scene itself
is authored in ``assets/round_belt_task/round_belt_scene.yaml`` (``SCENE_DIRECTIVES``).  Assets and
provenance are documented in ``assets/README.md`` and ``README.md``.  This module is the
public surface: everything below is what importers -- notably
``scripts/check_round_belt_task_poses.py`` -- read.
"""

from round_belt_task.constants import (
    ARM_TARGET_KD, ARM_TARGET_KE, ASSETS_DIR, BELT_CENTER, BELT_COLOR, BELT_NUM_ELEMENTS,
    BELT_RADIUS, BELT_SEMI_AXIS_X, BELT_SEMI_AXIS_Y, BELT_TRIGGER_BODY,
    BELT_TRIGGER_GRASP_DEPTH, BELT_TRIGGER_NEAREST_RADIUS, BELT_TRIGGER_POINT,
    BELT_TRIGGER_TOLERANCE, BOARD_COLOR, BOARD_PANEL_MIN_SPAN, BOARD_URDF, COMMON_ASSETS_DIR,
    FINGER_TARGET_KD, FINGER_TARGET_KE, GRIPPER_OPEN_MARGIN, HOLDER_URDF,
    LARGE_PULLEY_COLOR, LCM_GRIPPER_DRIVE_DAMPING, LCM_GRIPPER_DRIVE_EFFORT_LIMIT,
    LCM_GRIPPER_DRIVE_KD, LCM_GRIPPER_DRIVE_KE, LCM_GRIPPER_DRIVE_STOP,
    LCM_HAND_DRIVE_ARMATURE, LCM_HAND_DRIVE_EFFORT_LIMIT, LCM_HAND_DRIVE_KD, LCM_HAND_DRIVE_KE,
    LCM_HAND_DRIVE_LIMIT_KD, LCM_HAND_DRIVE_LIMIT_KE, LCM_HAND_DRIVE_MAX_SPEED,
    LCM_HAND_DRIVE_STALE_TIMEOUT, LCM_SIM_PARAMS,
    LCM_SOLVER_SUBSTEPS, LCM_SOLVER_VBD_ITERATIONS, LCM_UR_GRIPPER_TIP_Z, PANDA_ARM_URDF,
    PANDA_DEFAULT_Q,
    PANDA_FINGER_DEFAULT_Q, PANDA_FINGER_LABELS, PANDA_HAND_URDF, PANDA_JOINT_LABELS,
    PULLEY_MOUNT_COLOR, REPO_ROOT, ROBOTIQ_MJCF, ROUND_BELT_ASSETS_DIR, SCENE_DIRECTIVES,
    SMALL_PULLEY_COLOR, SMALL_PULLEY_MOUNT_LOCAL_XY, SMALL_PULLEY_MOUNT_RADIUS,
    TABLE_TOP_Z, TABLE_URDF, TABLE_VISUAL_LABEL, TABLETOP_COLLISION_THICKNESS,
    UR10_BASE_LABEL, UR10_DEFAULT_Q, UR10_JOINT_LABELS, UR10_URDF, UR10_WRIST3_D6,
    UR10_WRIST3_LABEL, X_LINK8_HAND, X_USDWRIST3_GRIPPER, X_USDWRIST3_URDFWRIST3,
    X_W_BOARD, X_W_HOLDER, X_W_PANDA, X_W_TABLE, X_W_UR10, X_WRIST3_GRIPPER,
)

from round_belt_task.joint_state import apply_default_joint_state
from round_belt_task.scene import JointConfig, SceneInfo, build_scene, make_builder

# Re-exported on purpose: this is how importers resolve a body/joint by label.
from utils.labels import body_index, joint_index

__all__ = [
    "ARM_TARGET_KD", "ARM_TARGET_KE", "ASSETS_DIR", "BELT_CENTER", "BELT_COLOR",
    "BELT_NUM_ELEMENTS", "BELT_RADIUS", "BELT_SEMI_AXIS_X", "BELT_SEMI_AXIS_Y",
    "BELT_TRIGGER_BODY", "BELT_TRIGGER_GRASP_DEPTH", "BELT_TRIGGER_NEAREST_RADIUS",
    "BELT_TRIGGER_POINT", "BELT_TRIGGER_TOLERANCE", "BOARD_COLOR",
    "BOARD_PANEL_MIN_SPAN", "BOARD_URDF", "COMMON_ASSETS_DIR", "FINGER_TARGET_KD",
    "FINGER_TARGET_KE", "GRIPPER_OPEN_MARGIN", "HOLDER_URDF",
    "JointConfig", "LARGE_PULLEY_COLOR", "LCM_GRIPPER_DRIVE_DAMPING",
    "LCM_GRIPPER_DRIVE_EFFORT_LIMIT", "LCM_GRIPPER_DRIVE_KD", "LCM_GRIPPER_DRIVE_KE",
    "LCM_GRIPPER_DRIVE_STOP", "LCM_HAND_DRIVE_ARMATURE", "LCM_HAND_DRIVE_EFFORT_LIMIT",
    "LCM_HAND_DRIVE_KD", "LCM_HAND_DRIVE_KE", "LCM_HAND_DRIVE_LIMIT_KD", "LCM_HAND_DRIVE_LIMIT_KE",
    "LCM_HAND_DRIVE_MAX_SPEED",
    "LCM_HAND_DRIVE_STALE_TIMEOUT", "LCM_SIM_PARAMS", "LCM_SOLVER_SUBSTEPS",
    "LCM_SOLVER_VBD_ITERATIONS", "LCM_UR_GRIPPER_TIP_Z", "PANDA_ARM_URDF",
    "PANDA_DEFAULT_Q",
    "PANDA_FINGER_DEFAULT_Q", "PANDA_FINGER_LABELS", "PANDA_HAND_URDF",
    "PANDA_JOINT_LABELS", "PULLEY_MOUNT_COLOR", "REPO_ROOT", "ROBOTIQ_MJCF",
    "ROUND_BELT_ASSETS_DIR", "SCENE_DIRECTIVES", "SMALL_PULLEY_COLOR",
    "SMALL_PULLEY_MOUNT_LOCAL_XY", "SMALL_PULLEY_MOUNT_RADIUS", "SceneInfo",
    "TABLETOP_COLLISION_THICKNESS", "TABLE_TOP_Z", "TABLE_URDF", "TABLE_VISUAL_LABEL",
    "UR10_BASE_LABEL", "UR10_DEFAULT_Q", "UR10_JOINT_LABELS", "UR10_URDF",
    "UR10_WRIST3_D6", "UR10_WRIST3_LABEL", "X_LINK8_HAND", "X_USDWRIST3_GRIPPER",
    "X_USDWRIST3_URDFWRIST3", "X_WRIST3_GRIPPER", "X_W_BOARD", "X_W_HOLDER", "X_W_PANDA",
    "X_W_TABLE", "X_W_UR10", "apply_default_joint_state", "body_index", "build_scene",
    "joint_index", "make_builder",
]
