"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_robotiq_command(object):

    __slots__ = ["utime", "speed", "force", "position"]

    __typenames__ = ["int64_t", "byte", "byte", "byte"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.speed = 0
        """ LCM Type: byte """
        self.force = 0
        """
        0-255
        LCM Type: byte
        """

        self.position = 0
        """
        0-255
        LCM Type: byte
        """


    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_robotiq_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qBBB", self.utime, self.speed, self.force, self.position))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_robotiq_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_robotiq_command._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_robotiq_command()
        self.utime, self.speed, self.force, self.position = struct.unpack(">qBBB", buf.read(11))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_robotiq_command in parents: return 0
        tmphash = (0x2d1342684da6c66f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_robotiq_command._packed_fingerprint is None:
            lcmt_robotiq_command._packed_fingerprint = struct.pack(">Q", lcmt_robotiq_command._get_hash_recursive([]))
        return lcmt_robotiq_command._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_robotiq_command._get_packed_fingerprint())[0]

