"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_robotiq_status(object):

    __slots__ = ["utime", "activation_status", "gripper_mode", "goto_status", "position", "speed", "force"]

    __typenames__ = ["int64_t", "boolean", "boolean", "boolean", "byte", "byte", "byte"]

    __dimensions__ = [None, None, None, None, None, None, None]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.activation_status = False
        """ LCM Type: boolean """
        self.gripper_mode = False
        """ LCM Type: boolean """
        self.goto_status = False
        """ LCM Type: boolean """
        self.position = 0
        """ LCM Type: byte """
        self.speed = 0
        """
        0-255
        LCM Type: byte
        """

        self.force = 0
        """
        0-255
        LCM Type: byte
        """


    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_robotiq_status._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbbbBBB", self.utime, self.activation_status, self.gripper_mode, self.goto_status, self.position, self.speed, self.force))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_robotiq_status._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_robotiq_status._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_robotiq_status()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.activation_status = bool(struct.unpack('b', buf.read(1))[0])
        self.gripper_mode = bool(struct.unpack('b', buf.read(1))[0])
        self.goto_status = bool(struct.unpack('b', buf.read(1))[0])
        self.position, self.speed, self.force = struct.unpack(">BBB", buf.read(3))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_robotiq_status in parents: return 0
        tmphash = (0x3b0c220559f87fa9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_robotiq_status._packed_fingerprint is None:
            lcmt_robotiq_status._packed_fingerprint = struct.pack(">Q", lcmt_robotiq_status._get_hash_recursive([]))
        return lcmt_robotiq_status._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_robotiq_status._get_packed_fingerprint())[0]

