"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_metadata(object):
    """
      Metadata struct for saving/loading trajectories
        All contents of lcmt_metadata besides name and description are 
        automatically filled when the LcmTrajectory object is created
    
    """

    __slots__ = ["git_dirty_flag", "datetime", "name", "description", "git_commit_hash"]

    __typenames__ = ["boolean", "string", "string", "string", "string"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.git_dirty_flag = False
        """
         git_dirty_flag is set to true if there are any uncommitted changes
        
        LCM Type: boolean
        """

        self.datetime = ""
        """ LCM Type: string """
        self.name = ""
        """ LCM Type: string """
        self.description = ""
        """ LCM Type: string """
        self.git_commit_hash = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_metadata._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.git_dirty_flag))
        __datetime_encoded = self.datetime.encode('utf-8')
        buf.write(struct.pack('>I', len(__datetime_encoded)+1))
        buf.write(__datetime_encoded)
        buf.write(b"\0")
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        __description_encoded = self.description.encode('utf-8')
        buf.write(struct.pack('>I', len(__description_encoded)+1))
        buf.write(__description_encoded)
        buf.write(b"\0")
        __git_commit_hash_encoded = self.git_commit_hash.encode('utf-8')
        buf.write(struct.pack('>I', len(__git_commit_hash_encoded)+1))
        buf.write(__git_commit_hash_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_metadata._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_metadata._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_metadata()
        self.git_dirty_flag = bool(struct.unpack('b', buf.read(1))[0])
        __datetime_len = struct.unpack('>I', buf.read(4))[0]
        self.datetime = buf.read(__datetime_len)[:-1].decode('utf-8', 'replace')
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        __description_len = struct.unpack('>I', buf.read(4))[0]
        self.description = buf.read(__description_len)[:-1].decode('utf-8', 'replace')
        __git_commit_hash_len = struct.unpack('>I', buf.read(4))[0]
        self.git_commit_hash = buf.read(__git_commit_hash_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_metadata in parents: return 0
        tmphash = (0x2980f75fa7e10d85) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_metadata._packed_fingerprint is None:
            lcmt_metadata._packed_fingerprint = struct.pack(">Q", lcmt_metadata._get_hash_recursive([]))
        return lcmt_metadata._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_metadata._get_packed_fingerprint())[0]

